database:
  # connection_string: "mssql+pyodbc://sqladmin:neunet-admin123@neunet-sql-server.database.windows.net:1433/CandidateInfoDB?driver=ODBC+Driver+18+for+SQL+Server"
  cosmos_db_uri: "https://neunet-cosmos-db.documents.azure.com:443/"
  cosmos_db_key: "hOlaV01rPLnOxzZf8LEbDUrs8osGbeG0R8xe3iuypkUHY5QIGsHq30eJtrrzNHmLTAM4p1nndfk8ACDbVoB1WQ=="
  cosmos_db_name: "CandidateInfoDB"
  resumes_container_name: "resumes"
  github_container_name: "githubAnalysis"
  ranking_container_name: "ranking"  
  job_description_container_name: "jobDetails"
  application_container_name: "applications"
  job_description_questionnaire_container_name: "jobDescriptionQuestionnaire"
  users_container_name: "users"

azure:
  storage_account_name: "neunetstotage"
  storage_account_key: "GtWXVE3Yh3+8d+fT7b3yG1rsZOIewEuGcjnjB/UyfEvLWX3l1sRClT0rgUnB7BTRgMGec2fro3H/+AStVnmygw=="

